// src/lib/components/Header.svelte
<script lang="ts">
	import { asset, resolve } from '$app/paths';
	import { page } from '$app/state';
	import Icon from '@iconify/svelte';
	import Nav from './Nav.svelte';

	const isBlog = $derived(page.url.pathname.startsWith('/blog'));
</script>

<header
	class="sticky top-0 left-0 z-10 mx-auto flex w-full max-w-6xl justify-between bg-bg py-4 pt-8 shadow-bg shadow-lg print:static print:mt-8 print:shadow-none"
>
	<div class="flex items-center gap-2 no-underline">
		<a class="flex items-center gap-2 font-proto text-xl no-underline" href={resolve('/')} aria-label="esskayesss home">
			<img class="size-7 opacity-90" src={asset('/logo.webp')} alt="contour logo" width="14" height="14" />
			<span class="font-proto text-xl leading-none">esskayesss</span>
		</a>
		{#if isBlog}
			<a
				class="h-fit rounded-full border border-accent-fg bg-dim-bg px-4 py-0.5 text-xs leading-none text-fg no-underline"
				href={resolve('/blog')}
			>
				BLOG
			</a>
		{/if}
	</div>
	<div class="flex items-center gap-4 text-3xl print:hidden">
		{#if isBlog}
			<a class="cursor-pointer text-fg no-underline" href={resolve('/blog/search')} aria-label="Search blog">
				<Icon icon="ph:magnifying-glass" aria-hidden="true" />
			</a>
		{/if}
		<Nav />
	</div>
</header>

// components/header/index.tsx
import Image from "next/image"
import {PiMagnifyingGlass} from "react-icons/pi"
import React from "react";
import {Navigation} from "@/components/ui/nav";
import Link from "next/link";

export const Header: React.FC<{blog?: boolean}> = ({blog = false}) => {
  return (
    <>
    <header
      className="print:mt-8 pt-8 flex shadow-bg shadow-lg justify-between w-full z-10 sticky py-4 top-0 left-0 z-9 bg-bg max-w-6xl mx-auto">
      <div className="flex items-center gap-2 no-underline">
        <Link href="/" className="flex font-proto text-xl items-center gap-2 no-underline">
          <Image src="/logo.webp" width="14" height="14" alt="contour logo" />
          <h1>esskayesss</h1>
        </Link>
        {blog && (
          <Link href="/blog" className='no-underline px-4 py-0.5 bg-dim-bg border border-accent-fg rounded-full text-xs h-fit'>
            BLOG
          </Link>
        )}
      </div>
      <div className="flex items-center gap-4 text-3xl print:hidden">
        {blog?<PiMagnifyingGlass className={`cursor-pointer`} />:null}
        <Navigation/>
      </div>
    </header>
    </>
  )
}
