// app/blog/page.tsx
import {BlogCard} from "@/components/ui/blog/card";
import Link from "next/link";
import { getAllBlogPosts, getLatestBlogSlugs } from "@/lib/blogs";

import type {Metadata} from "next";

export const metadata: Metadata = {
  title: "blog | esskayesss.",
  description: "A collection of blog posts.",
  keywords: [
    "Saurabh",  "Saurabh Sharma", "esskayesss", "esskayesss_",
    "SWE", "Portfolio", "Projects", "Technical Blog", "Programming",
  ],
  metadataBase: new URL("https://esskayesss.dev/projects"),
};

export default async function BlogHome() {
  const sortedSlugs = await getLatestBlogSlugs()
  const blogs = await getAllBlogPosts()
  return (
    <main>
      <div className={'section'}>
        <div className="heading">
          <h1>Latest Articles</h1>
          <Link href={`/blog/archive`}>See all</Link>
        </div>
        <div className="content">
          {sortedSlugs.length === 0 && <p>I'm just a chill guy.</p>}
          {sortedSlugs.map((slug, _idx) => (
            <BlogCard key={_idx} {...blogs[slug]} />
          ))}
        </div>
      </div>
    </main>
  );
}

// src/routes/blog/+page.svelte
<script lang="ts">
	import { resolve } from '$app/paths';
	import { blogPosts } from '$lib/blogs';
	import BlogCard from '$lib/components/BlogCard.svelte';
	import { canonicalUrl } from '$lib/site';

	const description = 'Technical notes, projects, and experiments by Saurabh Sharma.';
</script>

<svelte:head>
	<title>blog · esskayesss.</title>
	<meta name="description" content={description} />
	<meta property="og:title" content="blog · esskayesss." />
	<meta property="og:description" content={description} />
	<meta property="og:url" content={canonicalUrl('/blog')} />
	<link rel="canonical" href={canonicalUrl('/blog')} />
</svelte:head>

<section>
	<div class="heading">
		<h1>blog</h1>
		<div class="flex items-center gap-4">
			<a href={resolve('/blog/search')}>Search</a>
			<a href={resolve('/blog/archive')}>Archive</a>
		</div>
	</div>

	<div class="content">
		{#if blogPosts.length > 0}
			{#each blogPosts as post (post.slug)}
				<BlogCard {post} />
			{/each}
		{:else}
			<p>No posts published yet.</p>
		{/if}
	</div>
</section>
