// components/ui/nav/index.tsx
'use client';

import {PiList} from "react-icons/pi";
import React from "react";
import Link from "next/link";
import {GrDocumentPdf} from "react-icons/gr";
import {IoCloseOutline} from "react-icons/io5";
import {usePathname} from "next/navigation";

const nav_links = [
  {title: 'home', href: '/'},
  {title: 'projects', href: '/projects'},
  {title: 'blog', href: '/blog'},
]

const NavigationMenu: React.FC<{
  className?: string | undefined,
  onClick: () => void
}> = ({className, onClick}) => {
  const pathname = usePathname();

  return (
    <>
      <div className={`w-screen h-screen fixed left-0 top-18 z-50 backdrop-blur-sm ${className}`} onClick={onClick}></div>
      <div
        className={`${className} absolute z-50 right-0 top-full my-4 py-10 px-8 bg-bg border-2 border-accent-fg shadow-xl`}>
        <nav
          className={'flex flex-col gap-6 items-end font-proto *:no-underline text-xl' +
            ' *:flex *:gap-1 *:items-center *:whitespace-nowrap *:px-2' +
            ' min-w-60'}>
          {
            nav_links.map(({title, href}, _index) => {
              return (
                <Link
                  href={href} key={title}
                  className={`text-fg hover:bg-blue-bg ${pathname === href ? 'bg-dim-bg !text-blue-fg' : ''}`}
                  onClick={onClick}
                >
                  {title}
                </Link>
              );
            })
          }
          <a href={'/resume.pdf'} className={'hover:bg-ghost'} onClick={onClick}>resume <GrDocumentPdf
            className={`text-lg`}/> </a>
          <Link href={'/support'} className={`bg-yellow-bg text-yellow-fg`} onClick={onClick}>
            support me
          </Link>
        </nav>
      </div>
    </>
  )
}

export const Navigation: React.FC = () => {
  const [isMenuOpen, setIsMenuOpen] = React.useState(false);

  const openMenu = () => {
    setIsMenuOpen(true);
    document.body.style.overflow = "hidden"
  }

  const closeMenu = () => {
    setIsMenuOpen(false);
    document.body.style.overflow = "auto"
  }

  return (
    <div className={'relative'}>
      {isMenuOpen?
        <IoCloseOutline className={'text-3xl cursor-pointer'} onClick={() => closeMenu()} />:
        <PiList className="text-3xl cursor-pointer" onClick={() => openMenu()} />
      }
      <NavigationMenu
        className={`${isMenuOpen ? 'visible' : 'invisible'}`}
        onClick={() => closeMenu()}
      />
    </div>
  )
}

// src/lib/components/Nav.svelte
<script lang="ts">
	import { asset, resolve } from '$app/paths';
	import { page } from '$app/state';
	import Icon from '@iconify/svelte';

	const links = [
		{ label: 'home', href: resolve('/') },
		{ label: 'projects', href: resolve('/projects') },
		{ label: 'blog', href: resolve('/blog') }
	];

	let isOpen = $state(false);

	const closeMenu = () => {
		isOpen = false;
	};

	const toggleMenu = () => {
		isOpen = !isOpen;
	};

	const isActive = (href: string) => {
		const pathname = page.url.pathname;
		return href === resolve('/') ? pathname === href : pathname === href || pathname.startsWith(`${href}/`);
	};

	$effect(() => {
		document.body.style.overflow = isOpen ? 'hidden' : '';

		return () => {
			document.body.style.overflow = '';
		};
	});
</script>

<div class="relative print:hidden">
	<button
		type="button"
		class="relative z-50 flex text-3xl text-accent-fg hover:text-fg"
		aria-label={isOpen ? 'Close menu' : 'Open menu'}
		aria-expanded={isOpen}
		onclick={toggleMenu}
	>
		<Icon icon={isOpen ? 'ph:x' : 'ph:list'} aria-hidden="true" />
	</button>

	{#if isOpen}
		<button
			type="button"
			class="fixed top-0 left-0 z-40 h-screen w-screen cursor-default bg-transparent backdrop-blur-sm"
			aria-label="Close menu backdrop"
			onclick={closeMenu}
		></button>
		<div class="absolute top-full right-0 z-50 my-4 border-2 border-accent-fg bg-bg px-8 py-10 shadow-shell">
			<nav class="flex min-w-60 flex-col items-end gap-6 font-proto text-xl" aria-label="Primary navigation">
				{#each links as link (link.href)}
					<a
						class={`flex items-center gap-1 px-2 whitespace-nowrap no-underline hover:bg-blue-bg hover:no-underline ${
							isActive(link.href) ? 'bg-dim-bg text-blue-fg' : 'text-fg'
						}`}
						href={link.href}
						onclick={closeMenu}
					>
						{link.label}
					</a>
				{/each}
				<a
					class="flex items-center gap-1 px-2 whitespace-nowrap text-fg no-underline hover:bg-ghost hover:no-underline"
					href={asset('/resume.pdf')}
					onclick={closeMenu}
				>
					resume <Icon class="text-lg" icon="ph:file-pdf" aria-hidden="true" />
				</a>
				<a
					class="flex items-center gap-1 bg-yellow-bg px-2 whitespace-nowrap text-yellow-fg no-underline hover:text-yellow-fg hover:no-underline"
					href={resolve('/support')}
					onclick={closeMenu}
				>
					support me
				</a>
			</nav>
		</div>
	{/if}
</div>
